name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - 3xui2.9.x
          - 3xui3.0.x
          - 3xui3.1.x
          - sui1.x
          - xuiold
        goarch:
          - amd64
          - arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Prepare source
        run: |
          cp plugin/plugin.go plugin/${{ matrix.version }}/plugin.go

      - name: Build
        run: |
          mkdir -p dist

          cd plugin/${{ matrix.version }}

          export CGO_ENABLED=0
          export GOOS=linux
          export GOARCH=${{ matrix.goarch }}

          OUTPUT=xboard2xui-${{ matrix.version }}-linux-${GOARCH}

          go build -ldflags "-s -w" -o $OUTPUT .

          zip ../../dist/${OUTPUT}.zip $OUTPUT

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.version }}-${{ matrix.goarch }}
          path: dist/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Prepare files
        run: |
          mkdir upload
          find dist -name "*.zip" -exec cp {} upload/ \;

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*.zip
